version: '3.8'

services:
  web:
    build: .
    ports:
      - "8088:80"  # เข้าเว็บผ่าน http://localhost:8080
    volumes:
      - .:/var/www/html/  # ทำให้เวลาเราแก้โค้ดหรือเปลี่ยนรูป หน้าเว็บจะอัปเดตทันที